version: '3.4'

services:
    postgres:
        image: eu.gcr.io/docker-223614/ftsmb_postgres:latest
        build: .
        volumes:
            - postgres:/var/lib/data/postgres
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        secrets:
            - postgres_password
        ports:
            - '5432:5432'

volumes:
    postgres: ~

secrets:
    postgres_password:
        external: true
