version: '3.4'

services:
    postgres:
        build: .
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/data/postgres
            - ./hba.conf:/etc/postgres.hba
            - ./postgres.conf:/etc/postgres.conf
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        secrets:
            - postgres_password

volumes:
    postgres: ~

secrets:
    postgres_password:
        file: .postgres_password
